# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Valentin Ilie
tagline:             'maths and physics'
description:         'What a fine day for science.'
url:                 http://vilie.github.io
#baseurl:             ''
paginate:            5
comments:            true
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Valentin I.
  url:               https://vilie.github.io
  email:             valentin.ilie@gmail.com

# Custom vars
version:             1.0.0
